const int size =101;
const int num = 100;
double L = 5;
double m = 0.2;
double Ci = 2090;
double roi = 910;
double Cw = 4190;
double row = 1000;
double Croi = Ci * roi;
double Crow = Cw * row;
double Csc = 1920;
double rosc = 2000;
double Crosc = Csc * rosc;
double lamdaw = 0.58;
double lamdai = 2.23;
double lamdasc = 2;
double q = 3.34E5;
double Tq = 273.15;
double tau;
double oldTau;
double eps = .001;
double Tp = 273.15;
double T0 = 283.15;
double Tc = 263.15;
double tk = 173*60*60;//time in secands
double h[size];
double hs[size];
double x[size];
double T[size];
double alphaT[size];
double betaT[size];
double lamda[size];
double beta[size];
double dP[size];
double dM[size];
double teta[size];
double oldT[size];
double As[size];
double Bs[size];
double Cs[size];
double Ds[size];
double currTime = 0;
double alpha = 10.0f;